/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.KeyEvent;
import nsrfashion.LoyaltyCustomer;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author PrasadFTS
 */
public class CashierFrame extends javax.swing.JInternalFrame {

        Connection con;
        PreparedStatement pst;
        private ResultSet rs;
        double discount,loyaltyPoints,subTotal,TotalPrice,Balance;
        int saleID;
        nsrfashion.LoyaltyCustomer myCus=new LoyaltyCustomer();
        
        
        
    public CashierFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productCode = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQty = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtTotalItem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CustomerList = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtLoyaltyPoints = new javax.swing.JTextField();
        chkPoints = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        LAmount = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Product Code");

        productCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productCodeItemStateChanged(evt);
            }
        });
        productCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productCodeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Product Name");

        txtProductName.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Unit Price");

        txtUnitPrice.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Quantity");

        txtQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtQtyStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Total Price");

        txtTotalItem.setEditable(false);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(productCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(productCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1)
            .addComponent(jButton2)
        );

        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Customer ID:");
        jPanel3.add(jLabel6);

        CustomerList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CustomerListItemStateChanged(evt);
            }
        });
        CustomerList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CustomerListKeyPressed(evt);
            }
        });
        jPanel3.add(CustomerList);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Loyalty Points:");
        jPanel3.add(jLabel7);

        txtLoyaltyPoints.setEditable(false);
        jPanel3.add(txtLoyaltyPoints);

        chkPoints.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkPoints.setText("Use Loyalty Points");
        chkPoints.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPointsItemStateChanged(evt);
            }
        });
        chkPoints.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkPointsStateChanged(evt);
            }
        });
        chkPoints.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkPointsPropertyChange(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Customer ID", "Name", "Price", "Quantity", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTable1);

        jPanel4.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Cash (Rs.)");
        jPanel4.add(jLabel9);

        txtPay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPayFocusLost(evt);
            }
        });
        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });
        jPanel4.add(txtPay);

        LAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LAmount.setText("Sub Total (Rs.)");
        jPanel4.add(LAmount);

        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });
        jPanel4.add(txtSub);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Discount(%)");
        jPanel4.add(jLabel10);

        txtDiscount.setEditable(false);
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        jPanel4.add(txtDiscount);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Total Price (Rs.)");
        jPanel4.add(jLabel11);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel4.add(txtTotal);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Balance (Rs.)");
        jPanel4.add(jLabel12);

        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        jPanel4.add(txtBalance);

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Next Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(102, 255, 51));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("Cashier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkPoints)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addContainerGap(455, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayActionPerformed

    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed

    }//GEN-LAST:event_txtSubActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]
            {
                productCode.getSelectedItem().toString(),
                CustomerList.getSelectedItem().toString(),
                txtProductName.getText(),
                txtUnitPrice.getText(),
                txtQty.getValue().toString(),
                txtTotalItem.getText(),

            });
            calculatePrice(false);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
                DefaultComboBoxModel list = new DefaultComboBoxModel();
                DefaultComboBoxModel list2 = new DefaultComboBoxModel();
                //load Customers
                   try
                   {     
                      Class.forName("com.mysql.jdbc.Driver");
         
                      con = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
                      Statement s=null;
                      s = con.createStatement();
                      s.executeQuery("SELECT * FROM customer ORDER BY CustomerID");
                      rs = s.getResultSet();
                      list.addElement("Select");
                      while(rs.next())
                      {
                         String c = rs.getString("CustomerID");
                         list.addElement(c);
                      }
                      CustomerList.setModel(list);
                   }catch(SQLException err)
                   {
                      System.out.println(err);
                   } catch (ClassNotFoundException ex) 
                   {
                        Logger.getLogger(CashierFrame.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   
                   //load Products
                   try
                   {     
                      Class.forName("com.mysql.jdbc.Driver");
         
                      con = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
                      Statement s=null;
                      s = con.createStatement();
                      s.executeQuery("SELECT * FROM inventory where quantity>1 ORDER BY itemid");
                      rs = s.getResultSet();
                      list2.addElement("Select");
                      while(rs.next())
                      {
                         String c = rs.getString("itemid");
                         list2.addElement(c);
                      }
                      productCode.setModel(list2);
                   }catch(SQLException err)
                   {
                      System.out.println(err);
                   } catch (ClassNotFoundException ex) 
                   {
                        Logger.getLogger(CashierFrame.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   getSaleid();
                   AutoCompleteDecorator.decorate(CustomerList);
                   AutoCompleteDecorator.decorate(productCode);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        String cell = jTable1.getModel().getValueAt(row,0).toString();
        String sql ="" + cell;
        if(jTable1.getSelectedRowCount()==1)
        {
            tblModel.removeRow(jTable1.getSelectedRow());
            txtBalance.setText("");

            txtTotalItem.setText("");
            txtQty.setValue(Integer.parseInt("0"));
            txtSub.setText("");
            txtPay.setText("");
            txtTotal.setText("");
            //txtbill.setText("");

        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        myCus.updateNewLoyaltyPoints(txtSub.getText(),chkPoints.isSelected(),CustomerList.getSelectedItem().toString(),txtLoyaltyPoints.getText());
        
        try{
                    
            
            String query = "insert into sales(CustomerID,Cash,LoyaltyPoints,Discount,TotalPrice,Balance,subtotal,Date) values ('"+CustomerList.getSelectedItem().toString()+"','"+Double.parseDouble(txtPay.getText())+"','"+loyaltyPoints+"','"+discount+"','"+Double.parseDouble(txtTotal.getText())+"','"+Double.parseDouble(txtBalance.getText())+"','"+subTotal+"','"+java.time.LocalDate.now().toString()+"')";
            PreparedStatement ps = con.prepareStatement(query);
            ps.execute();
            getSaleid();
            int rowCount=jTable1.getRowCount();
            DefaultTableModel tblModel1 = (DefaultTableModel)jTable1.getModel();
            for(int i=0;i<rowCount;i++)
            {
                String query1 = "insert into salesdetails(ID,CustomerID,Item,UnitPrice,Quantity,Amount) values ('"+saleID+"','"+CustomerList.getSelectedItem().toString()+"','"+tblModel1.getValueAt(i, 2).toString()+"','"+Double.parseDouble(tblModel1.getValueAt(i, 3).toString())+"','"+Integer.parseInt(tblModel1.getValueAt(i, 4).toString())+"','"+Double.parseDouble(tblModel1.getValueAt(i, 5).toString())+"')";
                String UpdateStock="UPDATE inventory set quantity=quantity-'"+Integer.parseInt(tblModel1.getValueAt(i, 4).toString())+"'";
                PreparedStatement ps1 = con.prepareStatement(query1);
                ps1.execute();
                ps1=con.prepareStatement(UpdateStock);
                ps1.execute();
            }
            
        }catch(SQLException ex){
            System.out.println(ex);
        }    
        
                Path currentRelativePath = Paths.get("");
                String s = currentRelativePath.toAbsolutePath().toString();
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Map<String,Object> para=new HashMap<String,Object>();
                    para.put("OrderID", String.valueOf(saleID));
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
                    JasperDesign jd  = JRXmlLoader.load("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\Bill.jrxml");
                    JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\Bill.jrxml");

                    JasperPrint  jp = JasperFillManager.fillReport(jr,para,con);
                    JasperViewer.viewReport(jp,false);



                    }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        int rows=jTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for(int i = rows - 1; i >=0; i--)
        {
           model.removeRow(i); 
        }
        txtBalance.setText("");
        txtDiscount.setText("");
        txtLoyaltyPoints.setText("");
        txtPay.setText("");
        txtProductName.setText("");
        txtQty.setValue(0);
        txtSub.setText("");
        txtTotal.setText("");
        txtTotalItem.setText("");
        txtUnitPrice.setText("");
        CustomerList.setSelectedIndex(0);
        productCode.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CustomerListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CustomerListItemStateChanged
            txtLoyaltyPoints.setText(String.valueOf(myCus.getLoyaltyPOints(CustomerList.getSelectedItem().toString())));
    }//GEN-LAST:event_CustomerListItemStateChanged

    private void txtQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtQtyStateChanged
        txtTotalItem.setText(String.valueOf(Double.parseDouble(txtUnitPrice.getText())*Double.parseDouble(txtQty.getValue().toString())));
    }//GEN-LAST:event_txtQtyStateChanged

    private void txtPayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPayFocusLost
        txtBalance.setText(String.valueOf(Double.parseDouble(txtPay.getText())-Double.parseDouble(txtTotal.getText())));
    }//GEN-LAST:event_txtPayFocusLost

    private void chkPointsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkPointsStateChanged
        
    }//GEN-LAST:event_chkPointsStateChanged

    private void chkPointsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkPointsPropertyChange
        
    }//GEN-LAST:event_chkPointsPropertyChange

    private void chkPointsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPointsItemStateChanged
        calculatePrice(chkPoints.isSelected());
    }//GEN-LAST:event_chkPointsItemStateChanged

    private void productCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productCodeItemStateChanged
        String pCode = productCode.getSelectedItem().toString();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/loyaltycustomer","root","");
                pst = con.prepareStatement("select * from inventory where itemid=?");
                pst.setString(1, pCode);
                rs = pst.executeQuery();

                if(rs.next())
                {
                    txtProductName.setText(rs.getString("brandName")+" "+rs.getString("type"));
                    txtUnitPrice.setText(String.valueOf(rs.getDouble("itemprice")));
                    SpinnerNumberModel spm = (SpinnerNumberModel)txtQty.getModel();
                    spm.setMaximum(rs.getInt("quantity"));
                }
                
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CashierFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_productCodeItemStateChanged

    private void CustomerListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomerListKeyPressed
        if(evt. getKeyCode() == KeyEvent. VK_ENTER) {
            txtLoyaltyPoints.setText(String.valueOf(myCus.getLoyaltyPOints(CustomerList.getSelectedItem().toString())));
        }
    }//GEN-LAST:event_CustomerListKeyPressed

    private void productCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productCodeKeyPressed
        if(evt. getKeyCode() == KeyEvent. VK_ENTER) {
        String pCode = productCode.getSelectedItem().toString();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/loyaltycustomer","root","");
                pst = con.prepareStatement("select * from inventory where itemid=?");
                pst.setString(1, pCode);
                rs = pst.executeQuery();

                if(rs.next())
                {
                    txtProductName.setText(rs.getString("brandName")+" "+rs.getString("type"));
                    txtUnitPrice.setText(String.valueOf(rs.getDouble("itemprice")));
                    SpinnerNumberModel spm = (SpinnerNumberModel)txtQty.getModel();
                    spm.setMaximum(rs.getInt("quantity"));
                }
                
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(CashierFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_productCodeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CustomerList;
    private javax.swing.JLabel LAmount;
    private javax.swing.JCheckBox chkPoints;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> productCode;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtLoyaltyPoints;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JSpinner txtQty;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalItem;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    private void calculatePrice(boolean isCheck) {
        double sum=0;
        if(isCheck)
        {
            
            for(int i = 0; i<jTable1.getRowCount(); i++)
            {
                sum = sum+Double.parseDouble(jTable1.getValueAt(i, 5).toString());
            }
            subTotal=sum;
            if(sum>5000 && sum<10000)
            {
                txtTotal.setText(Double.toString(sum*(95/100)));
                txtDiscount.setText("5");
            }
            else if(sum>10000)
            {
                txtTotal.setText(Double.toString(sum*(90/100)));
                txtDiscount.setText("10");
            }
            else
            {
                txtDiscount.setText("0");
            }
            discount=subTotal*(Double.parseDouble(txtDiscount.getText())/100.00);
            boolean isusePoints=chkPoints.isSelected();
            if(isusePoints==true)
            {
                loyaltyPoints=Double.parseDouble(txtLoyaltyPoints.getText());
                txtTotal.setText(Double.toString(subTotal-loyaltyPoints-discount));
            }
            else
            {
                loyaltyPoints=0;
                txtTotal.setText(Double.toString(subTotal+loyaltyPoints-discount));
            }
        }
        else
        {
        
            for(int i = 0; i<jTable1.getRowCount(); i++)
            {
                sum = sum+Double.parseDouble(jTable1.getValueAt(i, 5).toString());
            }
            subTotal=sum;
            if(sum>5000 && sum<10000)
            {
                txtTotal.setText(Double.toString(sum*(95/100)));
                txtDiscount.setText("5");
            }
            else if(sum>10000)
            {
                txtTotal.setText(Double.toString(sum*(90/100)));
                txtDiscount.setText("10");
            }
            else
            {
                txtDiscount.setText("0");
            }
            discount=(subTotal)*(Double.parseDouble(txtDiscount.getText())/100.00);
            boolean isusePoints=chkPoints.isSelected();
            if(isusePoints==true)
            {
                loyaltyPoints=Double.parseDouble(txtLoyaltyPoints.getText());
                txtTotal.setText(Double.toString(subTotal-loyaltyPoints-discount));
            }
            else
            {
                loyaltyPoints=0;
                txtTotal.setText(Double.toString(subTotal-loyaltyPoints-discount));
            }
        }
        txtSub.setText(String.valueOf(subTotal));
    }

    private void getSaleid() {
        try
                   {     
                      Class.forName("com.mysql.jdbc.Driver");
         
                      con = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
                      Statement s=null;
                      s = con.createStatement();
                      s.executeQuery("SELECT MAX(SaleID) as maxID FROM sales");
                      rs = s.getResultSet();
                      if(rs.next())
                      {
                         saleID = rs.getInt("maxID");
                      }
                   }catch(SQLException err)
                   {
                      System.out.println(err);
                   } catch (ClassNotFoundException ex) {
                Logger.getLogger(CashierFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}
