/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Dimension;
import javax.swing.UIManager;

/**
 *
 * @author PrasadFTS
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCashier = new javax.swing.JButton();
        btnSupMng = new javax.swing.JButton();
        btnCusMng = new javax.swing.JButton();
        btnUserMng = new javax.swing.JButton();
        btnSupOrder = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        Username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        btnCashier.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCashier.setText("Cashier");
        btnCashier.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });
        jPanel2.add(btnCashier);

        btnSupMng.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSupMng.setText("Supplier Management");
        btnSupMng.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSupMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupMngActionPerformed(evt);
            }
        });
        jPanel2.add(btnSupMng);

        btnCusMng.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCusMng.setText("Customer Management");
        btnCusMng.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCusMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusMngActionPerformed(evt);
            }
        });
        jPanel2.add(btnCusMng);

        btnUserMng.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUserMng.setText("User Management");
        btnUserMng.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUserMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMngActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserMng);

        btnSupOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSupOrder.setText("Supplier Orders");
        btnSupOrder.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSupOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupOrderActionPerformed(evt);
            }
        });
        jPanel2.add(btnSupOrder);

        btnInventory.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnInventory.setText("Inventory");
        btnInventory.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        jPanel2.add(btnInventory);

        btnReports.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnReports.setText("Reports");
        btnReports.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jPanel2.add(btnReports);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NRS Fashion ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(132, 50));

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1461, Short.MAX_VALUE)
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        Username.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 0, 0));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Username.setText("jLabel1");
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Username)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane7)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        CashierFrame frame = new CashierFrame();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnSupMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupMngActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        Supplier frame = new Supplier();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnSupMngActionPerformed

    private void btnSupOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupOrderActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        Orders frame = new Orders();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnSupOrderActionPerformed

    private void btnCusMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusMngActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        Customer frame = new Customer();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnCusMngActionPerformed

    private void btnUserMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMngActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        ManageCashier frame = new ManageCashier();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnUserMngActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        Reports frame = new Reports();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        jDesktopPane7.removeAll();
        jDesktopPane7.updateUI();
        Inventory frame = new Inventory();
        frame.setVisible(true);
        Dimension desktopSize = jDesktopPane7.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);
        jDesktopPane7.add(frame);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Username.setText(User.userName+" (Logout)");
        if(User.category.equals("Cashier"))
        {
            
            btnInventory.setEnabled(false);
            btnSupMng.setEnabled(false);
            btnSupOrder.setEnabled(false);
            btnUserMng.setEnabled(false);
        }
        else if(User.category.equals("User"))
        {
            
            btnInventory.setEnabled(false);
            btnSupMng.setEnabled(false);
            btnSupOrder.setEnabled(false);
            btnUserMng.setEnabled(false);
            btnCashier.setEnabled(false);
            btnCusMng.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UsernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnCusMng;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSupMng;
    private javax.swing.JButton btnSupOrder;
    private javax.swing.JButton btnUserMng;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
