/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PrasadFTS
 */
public class Reports extends javax.swing.JInternalFrame {

    Connection connection = null;
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setClosable(true);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Customer List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Supplier List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Supplier Orders");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("User List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Daily Sales");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        
        try{
            
            //---------Build Path------------
            //JasperDesign jd  = JRXmlLoader.load("\\"+s+"\\newMemberList.jrxml");
            //JasperReport jr = JasperCompileManager.compileReport("\\"+s+"\\newMemberList.jrxml");
            
            JasperDesign jd  = JRXmlLoader.load("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\CustomerList.jrxml");
            JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\CustomerList.jrxml");
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
            JasperPrint  jp = JasperFillManager.fillReport(jr,null,connection);
            JasperViewer.viewReport(jp,false);
            
            
            
            }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        
        try{
            
            //---------Build Path------------
            //JasperDesign jd  = JRXmlLoader.load("\\"+s+"\\newMemberList.jrxml");
            //JasperReport jr = JasperCompileManager.compileReport("\\"+s+"\\newMemberList.jrxml");
            
            JasperDesign jd  = JRXmlLoader.load("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\SupplierList.jrxml");
            JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\SupplierList.jrxml");
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
            JasperPrint  jp = JasperFillManager.fillReport(jr,null,connection);
            JasperViewer.viewReport(jp,false);
            
            
            
            }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        
        try{
            
            //---------Build Path------------
            //JasperDesign jd  = JRXmlLoader.load("\\"+s+"\\newMemberList.jrxml");
            //JasperReport jr = JasperCompileManager.compileReport("\\"+s+"\\newMemberList.jrxml");
            
            JasperDesign jd  = JRXmlLoader.load("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\SupplierOrders.jrxml");
            JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\SupplierOrders.jrxml");
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
            JasperPrint  jp = JasperFillManager.fillReport(jr,null,connection);
            JasperViewer.viewReport(jp,false);
            
            
            
            }
            
            catch(ClassNotFoundException | SQLException | JRException e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        
        try{
            
            //---------Build Path------------
            //JasperDesign jd  = JRXmlLoader.load("\\"+s+"\\newMemberList.jrxml");
            //JasperReport jr = JasperCompileManager.compileReport("\\"+s+"\\newMemberList.jrxml");
            
            JasperDesign jd  = JRXmlLoader.load("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\UserList.jrxml");
            JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\UserList.jrxml");
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
            JasperPrint  jp = JasperFillManager.fillReport(jr,null,connection);
            JasperViewer.viewReport(jp,false);
            
            
            
            }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Path currentRelativePath = Paths.get("");
                String s = currentRelativePath.toAbsolutePath().toString();
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Map<String,Object> para=new HashMap<String,Object>();
                    para.put("Date", java.time.LocalDate.now().toString());
                    connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/loyaltycustomer","root","");
                    JasperDesign jd  = JRXmlLoader.load("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\Sales.jrxml");
                    JasperReport jr = JasperCompileManager.compileReport("C:\\Users\\PrasadFTS\\Documents\\NetBeansProjects\\NSRFashion\\src\\UI\\Sales.jrxml");

                    JasperPrint  jp = JasperFillManager.fillReport(jr,para,connection);
                    JasperViewer.viewReport(jp,false);



                    }
            
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
